function getReturnMessage(code) {
    switch (code) {
        case 0:
            return "成功";
        case 40000:
            return "订单餐桌数为0";
        case 40001:
            return "餐桌已经被占用";
        case 40002:
            return "餐位已取消预留";
        case 40003:
            return "您正在提交的日期或餐段不合法";
        case 40004:
            return "您正在提交的日期{0}已经过期，在预定也没有什么意义";
        case 40005:
            return "您正在操作的餐位不存在,请从新加载数据。";
        case 40006:
            return "餐位其它订餐台标记操作中。";
        case 40007:
            return "餐位预留失败！";
        case 40008:
            return "要预定的餐桌已经被预定，请刷新订餐台";
        case 40009:
            return "订单提交失败";
        case 40010:
            return "正在操作的订单已经被标记客到。";
        case 40011:
            return "正在操作的订单已经被标记撤单。";
        case 40012:
            return "正在操作的订单已经空闲。";
        case 40013:
            return "当前操作的电话号码的客户档案不存在";
        case 40014:
            return "订单或餐桌为空";
        case 40015:
            return "要修改的订单不存在";
        case 40016:
            return "此餐位已经被其它客户留作。";
        case 40017:
            return "此餐位其它订餐台标记操作中。";
        case 40018:
            return "餐厅餐段设置错误，请检查：该餐段是否设置。";
        case 40019:
            return "餐厅餐段设置错误，请检查餐段是否重复。";
        case 40020:
            return "该手机客户档案是空的，请核对手机号。";
        case 40021:
            return "来电号码不存在";
        case 40022:
            return "来电号码已经被处理";
        case 40023:
            return "来电号码为空";
        case 40024:
            return "此手机号已被注册!";
        case 40025:
            return "手机号码无效";
        case 40026:
            return "此手机的验证码不存在";
        case 40027:
            return "您输入的验证码不匹配或已失效";
        case 40028:
            return "您输入的验证码已过期";
        case 40029:
            return "添加用户资料失败";
        case 40030:
            return "更新用户资料失败";
        case 40031:
            return "此用户资料不存在";
        case 40032:
            return "此餐厅不存在或代理商未设置";
        case 40033:
            return "此餐时未设置对应的分类";
        case 40034:
            return "此手机的客户档案不存在";
        case 40035:
            return "此餐厅未设置微信渠道";
        case 40036:
            return "餐厅不存在";
        case 40037:
            return "添加订单失败";
        case 40038:
            return "验证码添加失败";
        case 40039:
            return "验证码更新失败";
        case 40040:
            return "每个手机一天最多可验证5次";
        case 40041:
            return "姓氏为空";
        case 40042:
            return "姓名只允许输入中文或者拼音字母";
        case 40043:
            return "姓名只允许输入不超过5个汉字或者10个拼音";
        case 40044:
            return "备注长度不得超过50";
        case 40045:
            return "没权限取消选中餐桌";
        case 40046:
            return "人数必须大于0";
        case 40047:
            return "人数必须小于10000";
        case 40048:
            return "单位长度不能超过15个汉字或30个字符";
        case 40049:
            return "备注长度不能大于255个字符";
        case 40050:
            return "电话格式不正确";
        case 40051:
            return "人数必须是数字";
        case 40052:
            return "姓名不能为空";
        case 40053:
            return "红包可用";
        case 40054:
            return "红包已用";
        case 40055:
            return "红包过期";
        case 40056:
            return "公交信息为空";
        case 40057:
            return "预定金过大";
        case 50001:
            return "登录失败";
        case 50002:
            return "未授权操作";
        case 50003:
            return "登录时间超时";
        case 51000:
            return "服务器端异常";

    }
    return "未知的返回值类型";
}